[package]
name = "fspcp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.5", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
ignore = "0.4.31"
imagesize = "0.15.0"
rayon = "1.12.0"
parse-size = "1.1.0"
fs-err = "3.3.1"
anyhow = "1.0.104"
ctrlc = "3.5.2"
crossfire = "3.1.19"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true
